DB_URL=jdbc:h2:file:./data/school
DB_USERNAME=jaidhanush
DB_PASSWORD=1234

MAIL_USERNAME=systemalertservice01@gmail.com
MAIL_PASSWORD=gukejsnvlojiqmal

JWT_SECRET=SchoolEnrollmentJavaSpringProjecwithSecureSetup
