# ===============================
# DATABASE (H2 LOCAL)
# ===============================
DB_URL=jdbc:h2:file:./data/schooldb
DB_USERNAME=jaidhanush
DB_PASSWORD=jaidhanush@123

# ===============================
# JWT SECRET
# ===============================
JWT_SECRET=mysupersecuresecretkeythatismorethan32chars

# ===============================
# MAIL CONFIG (for testing)
# ===============================
MAIL_USERNAME=systemalertservice01@gmail.com
MAIL_PASSWORD=igfpmvhwcevnhyjf